// AWS Security Hub RDS.3: RDS DB instances should have encryption at rest enabled.
RawEntityMetadata
| where Environment == 'AWS' and Identifiers.Type == 'rds.dbinstance' // Verify in Categories.
| extend IsEncrypted = tobool(Record.StorageEncrypted)
| extend HealthStatus = iff(IsEncrypted == false, 'UNHEALTHY', 'HEALTHY')
| project Id, Name, Environment, Identifiers, AdditionalData, Record, HealthStatus