// AWS Security Hub SecretsManager.1: Secrets should have automatic rotation enabled.
RawEntityMetadata
| where Environment == 'AWS' and Identifiers.Type == 'secretsmanager.secret' // Verify in Categories.
| extend RotationEnabled = tobool(Record.RotationEnabled)
| extend HealthStatus = iff(RotationEnabled == false, 'UNHEALTHY', 'HEALTHY')
| project Id, Name, Environment, Identifiers, AdditionalData, Record, HealthStatus