// SHA DEFAULT_SERVICE_ACCOUNT_USED.
RawEntityMetadata
| where Environment == 'GCP' and Identifiers.Type == 'REPLACE_WITH_GCP_COMPUTE_INSTANCE_TYPE'
| mv-apply ServiceAccount = Record.serviceAccounts on (
    summarize UsesDefaultAccount = countif(
        tostring(ServiceAccount.email) endswith '-compute@developer.gserviceaccount.com'
    ) > 0
)
| extend HealthStatus = iff(UsesDefaultAccount, 'UNHEALTHY', 'HEALTHY')
| project Id, Name, Environment, Identifiers, AdditionalData, Record, HealthStatus